# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    # Specify the Xcode version to use
    macos:
        xcode: "11.0.0"
    working_directory: /Users/distiller/project
    environment:
        FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
        - add_ssh_keys:
        fingerprints:
            - "7f:54:2c:4e:e8:76:c6:ac:db:11:ac:0b:d3:6e:5d:63"
        - checkout
        - run: bundle install
                    
        - run:
            name: Build Application
            command: xcodebuild
            
workflows:
    version: 2
    build-deploy:
        jobs:
        - build-and-test
