# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.0
jobs:
  build:
    # Specify the Xcode version to use
    macos:
        xcode: "11.0.0"
        #    working_directory: ~/Bloomr
    override:
        - bundle install

    steps:
        - checkout
        
        - run:
            name: Fetch CocoaPods Specs
            command: |
                curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
        
#        - run:
#            name: Install CocoaPods
#            command: |
#                curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
#                bundle exec pod install
            
        - run:
            name: Build Application
            command: xcodebuild
