# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    # Specify the Xcode version to use
    macos:
        xcode: "11.0.0"
    working_directory: /Users/distiller/project/Bloomr
    environment:
        FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
        - checkout
        - run: bundle install
                    
        - run:
            name: Build Application
            command: xcodebuild
            
workflows:
    version: 2
    build-deploy:
        jobs:
        - build-and-test
        filters:
        branches:
          only: development
