# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bloomr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bloomr
    pod 'SwiftLint'
	pod 'SnapKit', '4.2.0'
	pod 'Kingfisher'
	pod 'Localize-Swift', '2.0.0'
	pod 'EmptyDataSet-Swift', '~> 4.2.0'
	pod 'RxSwift','4.4.0'
    pod 'RxCocoa','4.4.0'
    pod 'RxKeyboard'
	pod 'RxAtomic', '4.4.0'
    pod 'Moya/RxSwift', '11.0.2'
	pod 'SwiftyJSON', '4.2.0'
    pod 'CocoaLumberjack/Swift', '3.4.2'
    pod 'BadgeHub'
    pod 'BTNavigationDropdownMenu'
    pod 'YouTubePlayer', :git => 'https://github.com/weakfl/Swift-YouTube-Player.git', :branch => 'use-wkwebview'
    pod 'UITextView+Placeholder'
    pod 'IQKeyboardManager'
    pod 'GrowingTextView'
    pod 'Pulley'
    pod 'AppCenter'
    pod 'AppCenter/Distribute'
    pod 'IGListKit', '~> 3.0'
    pod 'Presentr'
    pod 'HMSegmentedControl'
    pod 'CropViewController'
    pod 'KWVerificationCodeView'
    pod 'SVProgressHUD'
    pod 'CryptoSwift'
  target 'BloomrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
