//
//  TextManager.swift
//  Bloomr
//
//  Created by Tan Tan on 8/4/19.
//  Copyright © 2019 phdv. All rights reserved.
//

import Foundation

struct TextManager {
    static var okayText = "OK"
    static var thankYou = "Thank You!"
    static var whatOnYourMind = "What's on your mind"
    static var tellSomeThing = "Tell some thing"
    static var chooseReportReasonText = "Choose a reason"
    static var unlikeContent = "Dont like this content"
    static var spamContent = "Content spam"
    static var cancelText = "Cancel"
    static var doneText = "Done"
    static var joinContestText = "Join Contest"
    static var contestRuleText = "Contest Rule"
    static var saveText = "Save"
    static var reportText = "Report"
    static var moreText = "More"
    static var addText = "Add"
    static var uploadText = "Upload"
    static var informationText = "Info"
    static var nextText = "Next"
    static var youAreText = "You Are"
    static var femaleText = "Female"
    static var maleText = "Male"
    static var profilePictureText = "Profile picture"
    static var coverPictureText = "Cover picture"
    static var achievementText = "Achievement"
    static var notificationText = "Notification"
    static var listText = "List"
    static var paymentText = "Payment"
    static var settingText = "Setting"
    static var informationAccountText = "Information Account"
    static var profileText = "Profile"
    static var changePasswordText = "Change Password"
    static var privacyText = "Privacy"
    static var blockListText = "Block List"
    static var settingAppText = "Setting Application"
    static var languageText = "Language"
    static var introduceText = "Introduce"
    static var faqText = "FAQ"
    static var communityText = "Glowie Community"
    static var glowieappText = "www.glowieapp.com"
    static var tempConditionText = "Temp Condition"
    static var feedbackText = "Feedback"
    static var warningText = "Warning"
    static var viewAlbumContestText = "View album contest"
    static var newRegisterText = "New Register"
    static var registerInFBText = "Register in Facebook"
    static var loginInFBText = "Login in Facebook"
    static var hasAccountText = "Has a account"
    static var noAccountText = "Dont have account"
    static var loginText = "Login"
    static var inputPhoneNumberText = "Input phone number"
    static var yourPhoneNumberText = "Your phone number"
    static var registerText = "Register"
    static var termpConditionPrefixText = "Bằng cách nhấn vào nút Đăng Ký, bạn đã đồng ý với"
    static var terms_privacyText = "các điều khoản sử dụng của Glowie"
    static var inputConfirmationCodeText = "Input confirmation code"
    static var confirmationCodeSendToPhoneText = "Confirmation code will be send to phone number"
    static var inputConfirmationPhoneText = "Input confirmation phone number"
    static var passwordText = "Password"
    static var inputPasswordText = "Input password"
    static var inputOTPText = "Input OTP"
    static var forgotPasswordText = "Forgot password"
    static var newPasswordText = "New password"
    static var confirmPasswordText = "Confirm password"
}
